# Generated by Django 4.2.6 on 2023-10-30 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=400)),
                ('ageRating', models.CharField(max_length=3)),
                ('totalBricks', models.CharField(max_length=4)),
                ('setNumber', models.CharField(max_length=7)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
