# Generated by Django 4.2.6 on 2023-11-22 13:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=600)),
                ('thumbnail', models.ImageField(blank=True, upload_to='')),
                ('ageRating', models.CharField(max_length=3)),
                ('setNumber', models.CharField(max_length=7)),
                ('totalBrickCount', models.CharField(max_length=4)),
                ('minifigureCount', models.CharField(default=0, max_length=2)),
                ('yearReleased', models.CharField(max_length=4)),
                ('satisfactionRating', models.IntegerField(default=0)),
                ('reviewCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('opinion', models.TextField(max_length=400)),
                ('rating', models.IntegerField(default=0)),
                ('dateCreated', models.DateTimeField(auto_now_add=True, null=True)),
                ('legoSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.legoset')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_app.member')),
            ],
        ),
        migrations.CreateModel(
            name='LegoImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('imageTitle', models.CharField(default='', max_length=30)),
                ('legoSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.legoset')),
            ],
        ),
    ]
