# Generated by Django 4.2.6 on 2023-11-03 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='legoset',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
