# Generated by Django 4.2.6 on 2023-11-03 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_legoset_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('opinion', models.TextField(max_length=400)),
                ('legoSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.legoset')),
            ],
        ),
    ]
