# Generated by Django 4.2.6 on 2023-11-03 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0005_legoset_averagerating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legoset',
            name='averageRating',
        ),
    ]
