# Generated by Django 4.2.6 on 2023-11-03 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0006_remove_legoset_averagerating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legoset',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
