# Generated by Django 4.2.6 on 2023-11-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0007_alter_legoset_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='legoset',
            name='averageRating',
            field=models.IntegerField(default=0),
        ),
    ]
