# Generated by Django 4.2.6 on 2023-11-04 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0009_rename_averagerating_legoset_satisfactionrating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='legoset',
            old_name='totalReviews',
            new_name='reviewCount',
        ),
        migrations.RenameField(
            model_name='legoset',
            old_name='totalBricks',
            new_name='totalBrickCount',
        ),
        migrations.RenameField(
            model_name='legoset',
            old_name='year',
            new_name='yearReleased',
        ),
        migrations.AddField(
            model_name='legoset',
            name='minifigureCount',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
