# Generated by Django 4.2.6 on 2023-11-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0011_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='review',
        ),
    ]
