# Generated by Django 4.2.6 on 2023-11-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0012_remove_member_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='review',
            field=models.ManyToManyField(to='customer_app.review'),
        ),
    ]
