# Generated by Django 4.2.6 on 2023-11-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0013_member_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='review',
            field=models.ManyToManyField(blank=True, to='customer_app.review'),
        ),
    ]
