# Generated by Django 4.2.6 on 2023-11-18 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0014_alter_member_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='review',
        ),
        migrations.AddField(
            model_name='review',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_app.member'),
        ),
    ]
