# Generated by Django 4.2.6 on 2023-11-20 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0015_remove_member_review_review_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legoset',
            name='image',
        ),
        migrations.CreateModel(
            name='LegoImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('legoSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.legoset')),
            ],
        ),
    ]
