# Generated by Django 4.2.6 on 2023-11-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0016_remove_legoset_image_legoimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='legoimages',
            name='imageTitle',
            field=models.CharField(default='', max_length=30),
        ),
    ]
