# Generated by Django 4.2.6 on 2023-11-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0017_legoimages_imagetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='legoset',
            name='thumbnail',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
