# Generated by Django 4.2.6 on 2023-11-20 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0020_alter_legoset_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='legoset',
            name='thumbnail',
        ),
    ]
