# Generated by Django 4.2.6 on 2023-11-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0021_remove_legoset_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='legoset',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
