# Generated by Django 4.2.6 on 2023-11-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0022_legoset_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legoset',
            name='thumbnail',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
