# Generated by Django 4.2.6 on 2023-11-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0023_alter_legoset_thumbnail_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=None),
        ),
    ]
