# Generated by Django 4.2.6 on 2023-11-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0027_review_datecreated'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='firstName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='member',
            name='lastName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
