# Generated by Django 4.2.6 on 2023-11-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0028_member_datecreated_member_firstname_member_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legoset',
            name='description',
            field=models.TextField(max_length=600),
        ),
    ]
