# Generated by Django 4.2.6 on 2023-11-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0029_alter_legoset_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legoset',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
