# Generated by Django 4.2.6 on 2023-11-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0033_alter_legoset_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legoset',
            name='thumbnail',
            field=models.ImageField(blank=True, default='images/defaultPhoto.png', upload_to=''),
        ),
    ]
